### PR TITLE
bridge/gitlab: handle all known notes types

### LINKED ISSUE #185: Gitlab importation - unhandled note type
When trying to import issues from Gitlab, it starts and then:

```
panic: unhandled note type

goroutine 1 [running]:
github.com/MichaelMure/git-bug/bridge/gitlab.(*gitlabImporter).ensureNote(0xc420290080, 0xc4201edfc0, 0xc4201a8aa0, 0xc42058a180, 0x0, 0x0)
```

It still successfully imported some bugs. :)

The failing bug may be titled with some accents, quotes and parentheses, I don't know if this could be the cause of the crash.

### PR DESCRIPTION
**Pull request by A-Hilaly**
fix #185

### CODE REVIEW

File: bridge/gitlab/import.go [hunk 1]
```diff
@@ -248,7 +248,14 @@ func (gi *gitlabImporter) ensureNote(repo *cache.RepoCache, b *cache.BugCache, n
 
 		return err
 
-	case NOTE_UNKNOWN:
```
Comment (MichaelMure) [inline bridge/gitlab/import.go]: `NOTE_UNKNOWN` would lead to a panic

Comment (A-Hilaly) [reply bridge/gitlab/import.go]: Yes agreed that's not a reason to panic. Added `NOTE_UNKNOWN` to the cases

**Comment by cgivord** [comment]
This patch got me through a successful importation of all my bugs ! :)
Thank you both for this, awesome job !!
