### PR TITLE
A command to list matching bug id from a prefix

### LINKED ISSUE #47: feat: a command to list matching bug id from a prefix
To be able to auto-complete bug id from a prefix, a hidden command to query the repo for matching id is necessary. 

`git bug ls-id [<prefix>]`

If no prefix is given, output all existing id.

### PR DESCRIPTION
**Pull request by sladyn98**
This file adds the ls-id command which returns
the bug id matching the prefix the user enters.
If no prefix entered it lists all the BugId's

Closes #47

### CODE REVIEW

File: commands/ls-id.go [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+	"strings"
+
+	"github.com/MichaelMure/git-bug/bug"
+	"github.com/spf13/cobra"
+)
+
+func runLsID(cmd *cobra.Command, args []string) error {
+
+	if len(args) < 1 {
+		ListAllID()
```
Comment (golangcibot) [inline commands/ls-id.go]: Error return value of `ListAllID` is not checked (from `errcheck`)
